---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kafka-admin-credentials
  namespace: prod
spec:
  encryptedData:
    KAFKA_PASSWORD: AgBZQELt/YA7EjGEPhPj+nvAtpuyOfjwni63hDHOVOIlGi/gvvof+sVgYInnmNXV9L4E8KUJUDxlbsXanvovkU+RTRTrsYVzTFtIeujX4nxfEh5frv3GQmGVjleAEjr4gTWcgknGJ7MrP3G8JftexNg/axC8pzIpXzViNlsjIJPqpzm1q6T9CqcqfOynHijQJMcFrHQZc/UUeR4+U/tJh/5KecgGosF5FW1fi399uwj5zIXqOkd4QFpDzX61LrT/h6bV10FoAO9DfIEsU/aTVfmqIfKXufaExscdzEDwCg1E6SQornF0eY87arRMgT3pbdaAODfjMZ6ZNzLgZIiJc0xJVeAxcW8TmxIzwwb9S0W2ikTNk7121YjzbLBQSXikW6DpGF8hPGjFfRaUxRpCLnY+Ueop5tnLkhdAkf+WIHfW5SnT5F85Pow18e7FpI+ccGh0+Lywkzr3o5Oku1IA+DBRJ5bfF4bG9C65mMw2DefqNs0Jvsi8hYVfhspfYp6ZZEwtj0PSSeUdfL2uPBs0eEdsSyiLVfCqxCo+r3w5uSJ86nKowyNVcXKy/bIHkJYk6eYs0JV2ruP80D+01/VpbEmLB4f3M2FJOWXZn4tz6XVv3YotwJdEGEKBlW2Bp9JR/3mnrOMVekYVsbDmIhJctyXJgebZclp+gg/OdY5bS955iOlmtA5XwNxMZaCFy+r/QmZnH4Ui9fpx+P5FsMBhM2Q=
    KAFKA_USERNAME: AgA05cwHGlx/GYzwfyjOUoCICz+YO4tBhQ2cECpDbwlk6rxAdQjh4ZW4MrpnKUzMOQW/WVGmF0izVGZgycg1nNEHdN/DUGaWYwQ3vnq/XmZ3bZOyVDFCEiOWUnOrUJbkG+kT0hYMRPhw14Xh50iaTlqLnhECVQyt46byQQhyGhhMsPH6Wajy6lGbysS3quYAj96rflxHlfgVj5VWgo2T73IbSULwyhybbhLtNH+S/hmMUVEspIdzmqvy2VFhEe0IUzU59ZIjI/bpd9INKiHoHe3/TGkzlVvh7Vdvc+aeohmgqHM0WfFXOGnKRzBOR/aTCO7b/O+58A14koLadkqsF/jx56pBdpgCKiQ1EolnDUypavd7Xfv8S/AdlzZJi9mE/eIAKsGD/ApPks0XLP0Pyig1fHS6C1IYtBIjOBV1NIvr/TiK6Msg8KpXykjY85RiqYoTnlQ04HiJO7hyVa9Q1H+Qmrj8b0VD+rGOH8vr2PhuYj7uowtCxD6Eq2cVFI9x5Zjor5cIflPvc3CL+ZnDzBrUhyvQSfi9OC9rY3Q8+rJOl8z3lQvICWZjWMfLeGdEEnUJB+4cPde2qUs9n6a74TkfB5z5XN9IVkdgfpvNZco6STy7IakcmsCSAj8pHwrDpjEDOrCVynEam/X+hYa/7gtRZHkgukrSV6fKLz6FtkmgfLQniT+gZSbs/DNKDTFtpNzMNkOIfbKthHg9Nw==
  template:
    metadata:
      creationTimestamp: null
      name: kafka-admin-credentials
      namespace: prod
    type: Opaque
