---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: order-service-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgBQ/Yw5YRQ9xTomANPm7/LRRRadhfEqnpttrXhwxB04Ns37mYTYVfBGWyB1DgMYnoGfpw8YOUxsUvTo84H7UAZTHPNDoPVgyu+9+I2jxuYzLko95x3caTdTbueo1Xc6/M6nYQOW7nb3hJq27HgoQ616fyxnJzr4Whetw3VyWY35ZBPDsNTuDAvF7Dj+87XYzPd00g/XoOntyHYW3oDwhqf5Yoi1nKwW1mcYRbz17OK6FYZ2//00gvilfI4nqhgy5S4GAG2GI9Cc/0tPPgcpXvTbS9t3lMq1c81YGmbsl77WHWGaZBcLQmTXj1R5XBM3yzbWeecOiqWN4boiVUvRPM2DTCPh5VUbBnHaFbZxUIruiKWe8tfo0lTexfD/dA0ubhUrqnnvEAgNXK3dGblN3HyTAjPyEKlyS7afNFUrfdFXsIcyZggfiFYbBOmo719K1hupi7BnTsi6XF1AKZpBL89akURXgp1lXmP7wyndlSq2pZX5y/kv2fdHaz3U0vL1dik7rSEnAIBkZD2S4gnRAHjiqJgFoYenkJP0ezmNYATA+IeKYm0Xir4OChkJ2eMDNg7VkdbDJbpxLE4I3RTjtsdxIBklVK6Pvc6jvEuxGqgrGVW6BZSjpFCwSJjPiv8xaOD2QKFmIQL56uO8jVpXnWVpiQ27W8Qou/fc7063lUzyWbcNlYJbI9t5nJxjZwpdTWb8XA6Nn0tje3rOSOHUYT0=
    DB_USERNAME: AgA5PK0lB0tHB0GycEj2olo21SWnfvtUYoaN82z7KPu15MPmi0opY2ruie0XB+mmRNoFDDp7f52Bm0E7YZBuR7Y7JuYcdFqwSN2w/BPynyL46dwrMPexf4DsgiG9UJvutavMLTCQqg3KbKj5raGuaOVWX2ROzstdaM7so9hHPPunzNK6s1bOtKGTYTBN+c1+pCxb+zLG005ANwuKUTkrVqeGWU5I7Ie/0XccXlgg6ujo0lLP2++fPBIx+lFr1QslOh86bWmqIXrSfFsevbHnOOPFIEBJ36/UpXGkwI0tShF/ktN4pcTopciQVocDP35qE0fWq2THEnLurDcmhsry6kJSa8YdWKlFXSSZG1xatdNtW5lKNpw/rW0VqeU4zweqbX15we2c4PHOBheUioG/KBiV1TXPf0mk53QMyzk18eqIoT4XmcukLLYc9gGzzO1NE7zmKvHGJuQAZ68ysClK+weTobA+F9y3zoRH6F5aofvSkfok5j3IGhSA2MjYneEd/UFJ2ozcyVCSfcMEyIvNbsJMV6LgCtqYt5Fuy+5Rhzb1wTZ2/3lydYBpk4Qek3O3AwcW3Q0IL8zEW+SVTbPfqmcEqaM8i2hJaOv2UQChDlgJHXduk3WoAtRvIQfNAtV5k0OFbtUqQRlqE8aNh9MgyUNSDToxr1QvHosOjy4n34qeoHOE4RpDIlQG+jO5qCS3I2lpNEM75jpqCA1xSJbKWWwQNWc=
  template:
    metadata:
      creationTimestamp: null
      name: order-service-db-credentials
      namespace: prod
    type: Opaque
