---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: payment-service-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgB/ahrORlsRdsG40Mm29h7Pbaa95ftupzb0GRvDkcRnvwwi4OtSWj+hvPdmptLrlBs2Z0NU0pcdT+D95WJWrKgpZHykk2aNDPZkDU42Ynx4YeeDTKkVjyKgxVypslkYL6DH/7m1gJ1u9RoR4lPW93l8FDH8Yiqo7Fzmhe+g1RgPxmBxozOcuqOp4ijSjMir5DfZ9TG4XEBjiA/4aUIuRGpBONc/WUzf9J7ZmaKxvI8IJ+4ezbwmAXjYS0jvim0cET1KcbQvqzZv+QT8Ll9GN0MCb3imf8SzBOE1A/Shq9//rKHmoLfafZANxiU6l5P8baWLILYMcv/ML1K1Db07UnFaC6LJHlPOKm9cAeSd7307zgkTE5XMJjxS8/ecNanb/Wx+c0bhaiuwsS4PxyqGv36Vbg+2pajx0KQWnpw27nv4JWLASPpnzwpZbdaict/WuwY2SH8biWFHcB2GbBdGcrSCfKTL8x9H3t/cwSVaJ8da6CbYfiXgEJuPbbHEIDuyKZ9CJ234izbovN3C5CyY29tB83UywqKL74dv+ZrrF1C8eJ7TJyi81TsxN2w9Fnxqal0DOPUbbnLoftvRCjdydJvs7nBA6YdxcCuChEVkK5sBddwXwp+ABnDQnphKRMKoYYQf64l/ZhVMZk6jVlkqkSYxU1bTgyq9M+7oLLGCapPhVbx7uW/61/dbxA/vuHe6BIR/6Lu+3fa8XrqEveW6mcg=
    DB_USERNAME: AgB7itQYmN2RE8STkYdb89ihfCi9K35Ox9pZCZhJIBAjd1km6kag2yoKYbv7uTF3lRV7ebrUrbtvRoIkroyRQ4wI4nR7r/gu4liFrCBXgnJ2XROxmAtdFdVcWOPaDVlzWVuCVLWyfR1PsC420I5cHWlbHMO1q9i1X0cY3FY1aILpr+vS19WL7AK5fpReRDNdOAFjeeBmiAGGUOBX617I1IA7GTfUh4Y7DbmmjhWSpOWAzEn6mgbIbcDt+NylSay88tl9rpdasxdInqXjNsc47wCfra7dRejPq5B/iu49I2v4dILWgUmom3eHAeDL/HlEa6ArbjB5zoV6cyFhdgYBSDx88mXOhTdrUIc3/1vge5mxphqGjMmt3YxiU4KbgZrPDg7RR+/sjaq2wiSL8GK/EK2jHhWdi9Jmh3FZBnE+r2FG0mlRFg8tPERvz8xMSwkC7IAYVRfTcXPBFo2BCRkQp17UtlnG5fKWilSXrn4pxsdKMsWnl+N6HrVDGmUKt0tBySuONelwmdFGH1RluNqY04amhVDokNZDTIx/bBgGolJ+1dYsTNCTmj+nhY+Tx50S+JgHE2PuYomYkvBjXdZ9w39ohseI2sGKUN4bBRi8M/2o7FDoQSb4MyB7BeuC7pMCIbCFljKJoUgxVj2fvkbPtvI6Av4pJV6SeznzrxAnFU0cuCDqPfOio0xy5Cnd5JQDQbeeykGZFYx1RgS7azNf9BPOPMGPPw==
  template:
    metadata:
      creationTimestamp: null
      name: payment-service-db-credentials
      namespace: prod
    type: Opaque
