---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: product-service-db-credentials
  namespace: dev
spec:
  encryptedData:
    DB_PASSWORD: AgAE19hBo360sPBFoKIqggyewpNvwGnf6FlUuOaDx94a/8cT8deF167lu4ajHAGIoC4cUaPA/NWzF5pS/S04MfVOYFrrTsJMydm11fQleM7Y/uVkjKawGJpKFsQXH7A0/kxZiKkijMtG1zw8+XAT5YoRnjoQGqQY5nGRK4xDxhgCDV9Pbu9tAm6d3xpUNysdQvOxJVcxYEVTtqcvZL+4AYflQcRcFoznZgmCwsY7DRgslG76EytJqOOq5hyRokho3WKXf9gY93kcVzUIuFsrCSSWCVf0hZMCIO2ur1LHaPgJ5tZr8QxcCVU3xT4Aaw2kIrxCxVMhV4XPN59J+XscJxA1Dv1J677RQY0YMCdqCdsLNswp6QDUXYuaKbaRZ4kgybgSCW/H/fpWNYRRaG9iKo4MbxG8FCccG3iyCqhKmIhY+BAaDtYrtrYGrvWSSopCGAh2MgxiR3owXw6TcvBFfMT4w6rFtf1oa7QhmZlzyMIX2eoDIOrTSWcQeZUQjCRYoddFZN402YLc7knd8rf0uZqZWcYkAZ/2saBa/0reWqlaDwsfJ7dblO0tgSC97dOSmn/YP016kY1OrYjpmvopFF1riaS8cbH0/X6EOVznr8bDrF9bsdk0lheQKY6AFbYDCv61YACxYjrF+Gi7AgY6IRwhz845VHKa+qmKIzajyUSaeWClHps6XQuMPMBW8KN7pA1q86eOxta90cNOFm8tcTg=
    DB_USERNAME: AgB6a1xQEGv3YvFK3SRrBLnKvCqJc4Pfrd2sl2glIbupR/ML9FddGHeOOdsT4RoTsCU2ve+lM8KDaqv0pPlFKqvzpFwwJzeE19vnfmYFlNxSTsSwmDygNjoZkGYUJ9Lp2a6dM8DSXQwbVIubtn3cq/6ThT2bA+U5jlQ6YifUCFdkRwQekoobfDQWjccqcPpCLaiwgyJ0GzfmoBI3ACYx4QmohLGlu5gJZ6Y29KFJCHL62Wd5SBkEilnlxEArJlQDDXLNQSGici4R9frHopUuUNSuacLCzc4nl1/bGrl3Gy7aHc5m/1Kpq00IT8IZZ6kDpfcVo0hlGMUNIzSweUAvkencSvvwBJ55xDvYf6t5+lEfDrH68tpJ9MkKT6lprBfg23z9qtm0XGFU9InDEqMNbF4qjLxLL3sgJUBr5zjbXWBniL2tjQ6ZUWxwPUvgIToDjjpKd9hj6eIUKWxDYYmxkULs3VM6A4IRmGv53/wFjcT6Q3FWPsEkI9+T1+VgHt0i2mDBARxehr1phYDZVNBlALqJoIDCOUZA5UJKLj7zaBniX4GbiUU8dAUCcnmvmCrvOKsO9SEoxICKORgUrSBqLaN4IMvIi9okb65ZYM8/c+ZISBcVJNnHdf/0FbRHqUVPObjNegidycn7Q4GOPSTyXB5AhgWHPQ1Cvb7PKWmudt0VUkM6I2NAlLmlRgRyRrWTZQ0eV6k2L+JoFv0guSfTddiLBJMxIA==
  template:
    metadata:
      creationTimestamp: null
      name: product-service-db-credentials
      namespace: dev
    type: Opaque
