---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: product-service-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgAUfHtc6g32kCftQgHxo82fFb7E6RBPxgcUR4y3ysE1c5yzHdQ9E2wQBp8CwT7HhxtDfkuSq2LxUWi2b4J5Nw/7lgHn1teqrKVUS1R1UCMpqrkJMJbbmajCr87tPI1sU60A1dusA7iOAQSexZsmjI76/Q8/Ycx5b9nxFhGPREbd2NiTZsvn7pqWCYfjV2MX+mJlTjcZVWfkmzpEBhCL2zHKT7DcKa0jO179tnSYtd/XHeq1GFOcpZ32Wze5Bky9VMhEpu2CZN8wGADd9AzYQaaR93X/iDUYEFdjsuHflTEoA8ekrIBEvBT+5/aCIvJsHOcwkH8vvIK8/c1nu3b8QW/mheqXuPsDyXFDQEoAYKFrNSUdqIbFSfu95xOugE9DPzwA2FcuqliryVhWW+eQQ0CCeGGulojHp2LtgXuZTzh/ZPcme4czYWyBc9jGG/gew7jLK/kiJqzfFXfeXEAXs42+9RX75Wz6G+146dgwpiAZUjKUJuc1ZHNn4AMKFJjPHUQ2xTjQGmx4CW2Roj5uLioP5QnQFIknN6/yTM8YJzNT3RuTINpC29gO2OtC/889Z9D0Ux0v4/DL138wcrYapNjiT7yrXegm2AvctbCDZ6Hd+VFRZtRjQW6xVoRdb7n35N4IP1ir4cajG6ExjHGROzlB+WcRjE4sVRGxy08dGwJYWaA03Bhg6RwGgfc88IOYAjjps0uxMmgK6TJdi3NyCxA=
    DB_USERNAME: AgCQTA20vLAHGy4FneGRhnsTED7tZwM4+Eks/FqWxherptYgxAbNAYZ4o6dOCamWafEDFqiSSRktae2OwjVEt6DhOAsUl0Ov7d+DCiM/dkJq4zXpy3EAjlsZvLYb8q8j/dW7J0pfaNbKWj4Vo5Sm+qDEcEwSCTdkIH26sZguNpCCyTy3S1enMGTVEAGavGbibKs5iqMcHcPDvXya03pM48BWrrFnUqfPSNl9h66fQYe4+H7XXv7vA6Uf1WB8PB4cSuOuBquXDBNP+F1W7xnfeJGE4Cz1qZ8m6gOvsCEElp2+uZaGs9pNFLzmfEb2Nt0oyYIa9oln3PnsME+dJfowqXt+i1h47SEpdtpdv/jelU5dSFsRKfRoZMp+7+uSJj961EKejoRTTDGQjJP7+4fPXYK0A8f/sbxGAr2JsECsTBGnIPLr4ZwnqQ31EHjUgRqjvR2FrzsmqJABf0Y1JOGf6uDK5CZhcA1/4034FEEebc05c4qHjs0x9EB2uxS6qUBdSZwHhqVNV3EDpkQ8FlOe5DikhPNCsCNgZYw7QFgXSoDtVmEXMkF4jQps/LsPqdtsXilY0r+cQL4ff5LLYUJKiIIj1zIOLjHS3MSZIC/w2/Bbjj4Dc0Jqa2sG8Ur0TeWry/8+no0Cd6otlHumB4Yzc83B9ENop+P/wKJG2tFXYIly+Noe3AEyBxkGo6S0CT5LuVde2gy0Aaxk2ZcuoYru7c31dbgDjQ==
  template:
    metadata:
      creationTimestamp: null
      name: product-service-db-credentials
      namespace: prod
    type: Opaque
