---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-service-db-credentials
  namespace: prod
spec:
  encryptedData:
    DB_PASSWORD: AgABKOfYZdbK08NGT5Ro8wDOYRzCqzUFfbGGcTPaRx21QrGm1QCcBh7ouPJkd5acWSTTaGKtuib6RY17zkJ6DfnY1lkXFDhdaT/2SPUrdol2ghy+jmKRll+/QGgj/N0hewUjOgOhwhZ39PdcM0GNkIWYRdLVdJnpDd6+d0Shgly9f4gz6K8vlU+L8yOXx7ElpDBqX4ksn4AgkxujkBT5BVMrK0nsOCZ5fbSHlv2Ht7PQS98gCpP2+ZEm0hAf/vkx/Rv3BwVAbQNQhv9TJOZK97dZ9YPHhGe4MrlbdSlG3DaJRJ9w2a/ZS4kOoJ2MB77TAB+59dCaU5NWPrj0Tjyprj6QNLMq06rJCeXHT9Ryz6BgEHCSOOQqVCjuy7xi6AkxYO0we+GoNJxRJSUWbVYaaa+4oixyBiFiFyJdzQgT4wUwY6NikHVxLy9nguwOQ69AwL4J77o5X0JkPfqFs96fURTP/fzCukY7i+hhrJ7CppW2mUjYk/Qi+cifQYxu2NIT8xjbB96P5odhsY65DndZX3xz/3H1qfau7AiL3nbZ7Tv5ZLMlVNusiSdjcMqMf/3z8tUVzWL0ds1abFBILp8EtmL8eseQThW8Cm2BuYCgjw9zwQJeRSwim8PUjkjrYMgtXdTJe12d1Uhqu1AFlVqvYDVbyzYCqfn3VeDX1wBrsgV2NFSauk82W7vay2kDsKG5Fpd+hTdkEvE22oUj5Vu4VKk=
    DB_USERNAME: AgAEovMNv8k742ZyHIPzPFmWXvwCL0kCrv4xBuSwFANnYv2jcqajbKrzLCxuptNPQZDioS7AHaseaN9YRuc632tBP+qKm1oBoA1vDwOp0DeuAl7T+AdW15I96lRpTQhp/uSYFSb3BDn+OBHjGpieiX2SQChxpmfrRA4eYXetrUNuD2HT1nmjc4n7gWg7+dE07j8ZRIVyAtNgPSVPpwiWnqcU78yK1FY8wp2P9hLUSRrYO5ckpROZoEX9mciQ6bx/VNzUdml9m9N1CIB2cJuQL5Wbv3pjRGtNyfeGRARJq7vUsHGQul0Q2MvSZs5ASt7eYIqXEOhT+5qQawcj9X73RNj2wCeK2NL8BH3MG3W6BOeke95sFVA13PWkyEGX1s+jm49gfRiyv4t1It9ir91g8JP+9P84NFQIATUOTcOUNUOIdz945JcvZxWi9mrE/EyVfxVQGtMqPNR7DlZY0HU8U6UN2zYcyQ/eZZjfpUb9q9ZUZaKw5Rz1Ih05tyEpObWyqdEC2XJ5O6v40EGrvT5pE0SybwKSrfgIwLnjyP8nsGplY8o4HBOnAu318h/Y4RGBUIEzqU/Ypt+9SN31aLjgovHwkhE+7WQoRTGFuyGw0QcMRr39+EFoiSNFuYCuoNraJ0BMwjccxndJmjBMfCJ4A0hDJoieFQC9Qf+HDOTkKsct7cYrZvrWD3VnY1paFyXXA8q6fHwJeDm/vWGEB64YLzCIqA==
  template:
    metadata:
      creationTimestamp: null
      name: user-service-db-credentials
      namespace: prod
    type: Opaque
