---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-service-db-credentials
  namespace: dev
spec:
  encryptedData:
    DB_PASSWORD: AgCOU/crTHwkzpY1/Dl295gf83B9DcAzv/KC+BuNx+HqyTvC778l1L97wTG1HOnoYYi5zlGs3F5RGoyhoKW6HI5pfGCKtGAtBoD1NrvRzEcyk46Q4wYPMmU0PmApBqfSfXHw0k1QfQjy+N21MwD+fFseVmzgc+qqJu1yaHT0WADTr1Yy/EZOTfFP5AhJ1hDJAZlZsUXkOiFDdPyW8dA9v3WW1wZ0M76z0EI8G94RI5rOk1RqhqoE4WMFbpevQIOZdSgf+vnuYReL5WHUxzbrJConNumPKOnQGMVn6g5DDA7elFzspO5EkDjasaVskriNnFrzYKBrrlnhJmwWbjj0WHHZKrN0dFS7QiEb96QSazL8shfKrGJNV6YYAnXvs/iqZ1ICfJdv5D8c3H5M0TJiONtQH2zCi3ZjyKxeyPuqChunMpuWpMWF8XDVD6DmMJT+l8VTcvwFBDGjo+FdKLNIapcsVectHROOkS+feJ915EsaG1cDedZvs3RUP7yXu3fArYkPPi48mx5TstIcsM3zdEMd67pyCzlpJjDr9R8uiFApjukCZYURoaE9WsUly0jw8ny0jt0hh8wYtddGDV0LgwlhYCZEesQz5poKf/7B/GV8tmzn/PmfXWzKBjnnRYn+JbVz3gXJ5womh60zXihf1MkBf8JaGY94KBRiZW9LAkOgJXAYE2ies9c0OPDqeADtPZcW92QzEEE8K18Pz8gClig=
    DB_USERNAME: AgByzL3le4J2mzC8fVSPY3k2tdw0BsexNcxCvImEcuCf2DIOr612YyzsfVDZM1u3SESy/otlDNO4VSpe/CvfMiCqxA8VxSsQMue5LGgbkH3iFRTsoBLDaX4UIGFAQxhjAlmmtHLRreuRqYyhRBVUWqySpL6Ruhne1I/JdRdmvRiP271FNlEmrNhWiUC4TD6W/SR54AQcpwvyL2yIwOZPSvo090rcTAB2l7JElSpJBy+zsV2d/iKNT6/QKlPpd783D3JbCY1gH75zLKEr+OdfwJ8k+Uc/cXCceGA/pQgqv0/rCNXcxeV3Qdd2eswuKDX5cfarJ28+09k0im3YC2zrhO0yytbnSZ1VqTdnOmsRiM6Rd+tdbCH1+ZNt2f4kMr+FOrE0hifZyHxD1LfWXPdAY7z8olsYhMK+tRrn0/ImiTaU2qDM0yFFboMvjyddi1KFBd3Zwm92mRd4HSyQnbp5uR0/G7JW6gpqvFY+7IQEkAJ2A/Bey+Hfaurwwjbo1d/tMadBBQ5f+cbvzE4mKviHCW1BSKdg0XwkWuPQNU/fXr5DHk9j1ebqeBG/Itt0mZ+bbyb18TnJI8ikTP7xhd5+hRp85svfk7NUJKzLuj5pFm8Gel1MiNB0/KJLAUB+MPejo6X7gr3nA3+Rj3+3sPTRj5R2iU0ssFEe/Fs4qJbBTz6isEjxHFN6xN4r9QkbI/QzvJSRC52KrLKlFKqvEIeRA0v3KQ==
  template:
    metadata:
      creationTimestamp: null
      name: user-service-db-credentials
      namespace: dev
    type: Opaque
